# Numpy Indexing

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[4]

4

In [5]:
#Slice notation
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [7]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Broadcast
#arr[0:5] = 100
#arr

In [10]:
#Broadcast
arr[4:9] = 50
arr

array([ 0,  1,  2,  3, 50, 50, 50, 50, 50,  9, 10])

In [11]:
#Reset the array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_array = arr[0:7]
slice_of_array

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
slice_of_array[:]

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
slice_of_array[:] = 35
slice_of_array

array([35, 35, 35, 35, 35, 35, 35])

In [15]:
arr

array([35, 35, 35, 35, 35, 35, 35,  7,  8,  9, 10])

In [16]:
#Specify a copy and stored in a separate variable so that the original variable wont by broad casting
arr_copy = arr.copy()
arr_copy

array([35, 35, 35, 35, 35, 35, 35,  7,  8,  9, 10])

In [17]:
arr_copy[:] = 35
arr_copy

array([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35])

In [18]:
arr

array([35, 35, 35, 35, 35, 35, 35,  7,  8,  9, 10])

## Indexing Matrix

In [19]:
arr_2d = np.array([[5, 10,15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
#Double bracket format
#array[row][col]
arr_2d[0][0]

5

In [21]:
arr_2d[2][1]

40

In [22]:
#Single Bracket
arr_2d[1]

array([20, 25, 30])

In [23]:
arr_2d[0]

array([ 5, 10, 15])

In [24]:
#Comma single bracket notation; for less prone to errors
#array[row,col]
arr_2d[2][2]


45

In [25]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [27]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

# #Conditional selection

In [28]:
arr2 = np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
bool_arr = arr2 > 3
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [30]:
arr2[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [31]:
arr2[arr2 >3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [32]:
arr2[arr2 < 3]

array([1, 2])

In [33]:
arr3_2d = np.arange(50).reshape(5,10)
arr3_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
arr3_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])