# Numpy Intro and Common Methods

In [1]:
import numpy as np

In [2]:
list = [1, 2, 3]

In [3]:
# Create numpy array from python object such as list
arr = np.array(list)
#print arr var to cast list into an array and return one dimensional array
arr

array([1, 2, 3])

In [4]:
# 2D array
list1 = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
list1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
two_dimensional = np.array(list1)
two_dimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((7,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.linspace(0,11, 10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [13]:
np.linspace(1,100, 15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(3,7)

array([[0.56596623, 0.33573386, 0.69900338, 0.19010478, 0.93356554,
        0.58378011, 0.31706337],
       [0.98495667, 0.74325692, 0.09306105, 0.02433181, 0.7938061 ,
        0.42208063, 0.82749399],
       [0.21856217, 0.86294177, 0.0359953 , 0.81937275, 0.00322976,
        0.46714635, 0.78804938]])

In [16]:
np.random.rand(5)


array([0.19628917, 0.96863933, 0.32707804, 0.50440027, 0.81168877])

In [17]:
#Return a samples from standard normal distribution
np.random.randn(10)

array([ 1.2160078 ,  1.34938912,  0.47520225, -1.61697276, -0.79968675,
        1.26472922,  1.00334617,  1.48448917, -0.84699696,  2.03959696])

In [18]:
np.random.randn(5,5)

array([[-0.09169875, -0.39015184,  0.55707521,  0.84276387, -1.33226417],
       [-0.0744051 , -1.28309771, -0.7222889 ,  0.16100431,  0.90071333],
       [ 0.94410939, -0.94891437, -0.2339247 ,  1.51074399, -0.30411903],
       [-0.52431976,  0.86821009,  0.00756209,  0.98462408,  0.96444735],
       [ 0.26235357, -0.81452529, -1.02170605, -0.87376495, -0.14986331]])

In [19]:
np.random.randint(0, 200, 10)

array([ 85, 129,  84,  43,  65,  90,  13, 198,  33, 143])

In [20]:
np.random.randint(0, 200)

131

In [21]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)
ranarr

array([17,  7,  3, 11, 12, 37, 45,  7, 28,  3])

In [23]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr

array([17,  7,  3, 11, 12, 37, 45,  7, 28,  3])

In [25]:
ranarr.max()

45

In [26]:
ranarr.argmax()


6

In [27]:
ranarr.argmin()


2

In [28]:
ranarr.shape


(10,)

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.randn(1)

array([0.55003458])

In [31]:
np.random.randn(25)

array([-1.40415057, -0.12542895,  0.54512853, -1.48821842, -1.52292785,
        0.02365498,  0.16564628, -0.98663308, -0.64849936,  0.29535011,
        0.83821479,  0.700402  ,  1.10848091,  0.44140203,  1.10263289,
       -0.48018752,  1.02843122,  0.62191231,  1.05711044, -0.89248246,
       -0.14525799, -1.19610928, -1.02409171, -0.44880816,  1.0450178 ])

In [32]:
a = np.linspace(0.01,1, 100)
b = a.reshape(10,10)
b

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [33]:
a = np.linspace(0,1, 20)
a

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [34]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [36]:
mat[3,4]

20

In [37]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [38]:
mat[4]

array([21, 22, 23, 24, 25])

In [39]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
sum1 = mat.sum()
sum1

325

In [41]:
#Vertical summation
mat.sum(0)

array([55, 60, 65, 70, 75])

In [42]:
#Horizontal summation
mat.sum(1)

array([ 15,  40,  65,  90, 115])