# Numpy Operation


In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#Arithmetic operation element by element
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
arr +10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr **2


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])